apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-file"
  namespace: "openshift-local-storage" 
spec:
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
          - ""
  storageClassDevices:
    - storageClassName: "localfile-sc"
      volumeMode: Filesystem
      devicePaths: 
        # NODE:compute-1.oss.labs
        # nvme0n1
        - /dev/disk/by-id/nvme-eui.01000000010000005cd2e41ee94d5051
        # NODE:compute-2.oss.labs
        # nvme0n1
        - /dev/disk/by-id/nvme-eui.01000000010000005cd2e425e94d5051
        # NODE:compute-3.oss.labs
        # nvme0n1
        - /dev/disk/by-id/nvme-eui.01000000010000005cd2e4bcb54d5051

